export const localIconUrlMap = {
  "Biomass Burner": "./images/icons/300px-Biomass_Burner.webp",
  "Alien Power Augmenter": "./images/icons/Alien_Power_Augmenter.webp",
  "Coal Generator": "./images/icons/Coal-Powered_Generator.webp",
  "Fuel Generator": "./images/icons/Fuel-Powered_Generator.webp",
  "Geothermal Generator": "./images/icons/Geothermal_Generator.webp",
  "Nuclear Power Plant": "./images/icons/Nuclear_Power_Plant.webp",
}

export const iconUrlMap = {
  "ENERGY": "https://raw.githubusercontent.com/deniszholob/icons-factorio/refs/heads/main/factorio-icons/core/icons/tooltips/tooltip-category-electricity.png",
  "Biomass Wood": "https://raw.githubusercontent.com/KirkMcDonald/satisfactory-calculator/refs/heads/master/images/Biomass.png",
  "Biomass Leaves": "https://raw.githubusercontent.com/KirkMcDonald/satisfactory-calculator/refs/heads/master/images/Biomass.png",
  Pipeline: "https://satisfactory.wiki.gg/images/d/d3/Clean_Pipeline_Mk.1.png",
  "Non Fissile Uranium": "https://satisfactory.wiki.gg/images/e/ef/Non-Fissile_Uranium.png",
  "Biochemical Sculptor":"https://satisfactory.wiki.gg/images/d/df/Biochemical_Sculptor.png",
  "Iodine-Infused Filter": "https://satisfactory.wiki.gg/images/e/ea/Iodine-Infused_Filter.png",
  "Main Portal": "https://satisfactory.wiki.gg/images/Main_Portal.png",
  // "Solid Biofuel": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SolidBiofuel_256.png",
  // "Smart Plating": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_1_256.png",
  // "Versatile Framework": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_2_256.png",
  // "Automated Wiring": "https://static.satisfactory-calculator.com/img/gameUI/SpelevatorPart_3_256.png",
  // "Modular Engine": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_4_256.png",
  // "Adaptive Control Unit": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_5_256.png",
  // Chainsaw: "https://static.satisfactory-calculator.com/img/gameUI/Chainsaw_256.png",
  // Water: "https://static.satisfactory-calculator.com/img/gameUI/LiquidWater_Pipe_256.png",
  // "Water Extractor": "https://static.satisfactory-calculator.com/img/gameUI/Waterpump_256.png",
  // "Sulfuric Acid": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidSulfuricAcid_Pipe_256.png",
  // "Heavy Oil Residue":
  //   "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidHeavyOilResidue_Pipe_256.png",
  // "Polymer Resin": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_PolymerResin_256.png",
  // "Alumina Solution": "https://static.satisfactory-calculator.com/img/gameUI/LiquidAlumina_Pipe_256.png",
  // "Aluminum Scrap": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_AluminiumScrap_256.png",
  // "Uranium Pellet": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_UraniumPellets_256.png",
  // "Petroleum Coke": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_PetroleumCoke_256.png",
  // Turbofuel: "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidTurboFuel_Pipe_256.png",
  // Fuel: "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidFuel_Pipe_256.png",
  // "Crude Oil": "https://static.satisfactory-calculator.com/img/gameUI/LiquidOil_Pipe_256.png",
  // Concrete: "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_Concrete_256.png",
  // "Iron Ore": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_iron_new_256.png",
  // "Copper Ore": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_copper_new_256.png",
  // "Caterium Ore": "https://static.satisfactory-calculator.com/img/gameUI/CateriumOre_256.png",
  // "Quartz Crystal": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_QuartzResource_256.png",
  // "AI Limiter": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_AILimiter_256.png",
  // Motor: "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_Engine_256.png",
  // "Circuit Board": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_CircuitBoard_256.png",
  // "Encased Uranium Cell": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_NuclearCell_256.png",
  // "Coal Generator": "https://static.satisfactory-calculator.com/img/gameUI/CoalGenerator_256.png",
  // "Aluminum Casing": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_AluminiumCasing_256.png",
  // "Assembly Director System":
  //   "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_AssemblyDirectorSystem_256.png",
  // Blender: "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_Blender_256.png",
  // "Magnetic Field Generator":
  //   "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_MagneticFieldGenerator_256.png",
  // "Smokeless Powder": "https://static.satisfactory-calculator.com/img/gameUpdate6/IconDesc_GunpowderMk2_256.png",
  // "Nitrogen Gas": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_NitricAcid_256.png",
  // "Cooling System": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_CoolingSystem_256.png",
  // "Fused Modular Frame": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_FusedModularFrame_256.png",
  // "Particle Accelerator": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_HadronCollider_256.png",
  // "Copper Powder": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_CopperDust_256.png",
  // "Uranium Waste": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_NuclearWaste_256.png",
  // "Pressure Conversion Cube": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_ConversionCube_256.png",
  // "Nuclear Power Plant": "https://static.satisfactory-calculator.com/img/gameUI/NuclearPowerplant_256.png",
  // "Uranium Fuel Rod": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_NuclearFuelRod_256.png",
  "": "",
};
