export const iconUrlMap = {
    "Pipeline": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_Pipes_256.png",
    "Solid Biofuel": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SolidBiofuel_256.png",
    "Smart Plating": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_1_256.png",
    "Versatile Framework": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_2_256.png",
    "Automated Wiring": "https://static.satisfactory-calculator.com/img/gameUI/SpelevatorPart_3_256.png",
    "Modular Engine": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_4_256.png",
    "Adaptive Control Unit": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_SpelevatorPart_5_256.png",
    "Chainsaw": "https://static.satisfactory-calculator.com/img/gameUI/Chainsaw_256.png",
    "Water": "https://static.satisfactory-calculator.com/img/gameUI/LiquidWater_Pipe_256.png",
    "Water Extractor": "https://static.satisfactory-calculator.com/img/gameUI/Waterpump_256.png",
    "Sulfuric Acid": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidSulfuricAcid_Pipe_256.png",
    "Heavy Oil Residue": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidHeavyOilResidue_Pipe_256.png",
    "Polymer Resin": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_PolymerResin_256.png",
    "Alumina Solution": "https://static.satisfactory-calculator.com/img/gameUI/LiquidAlumina_Pipe_256.png",
    "Aluminum Scrap": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_AluminiumScrap_256.png",
    "Uranium Pellet": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_UraniumPellets_256.png",
    "Petroleum Coke": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_PetroleumCoke_256.png",
    "Turbofuel": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidTurboFuel_Pipe_256.png",
    "Fuel": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_LiquidFuel_Pipe_256.png",
    "Crude Oil": "https://static.satisfactory-calculator.com/img/gameUI/LiquidOil_Pipe_256.png",
    "Concrete": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_Concrete_256.png",
    "Iron Ore": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_iron_new_256.png",
    "Copper Ore": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_copper_new_256.png",
    "Caterium Ore": "https://static.satisfactory-calculator.com/img/gameUI/CateriumOre_256.png",
    "Quartz Crystal": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_QuartzResource_256.png",
    "A.I. Limiter": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_AILimiter_256.png",
    "Motor": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_Engine_256.png",
    "Circuit Board": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_CircuitBoard_256.png",
    "Encased Uranium Cell": "https://static.satisfactory-calculator.com/img/gameUI/IconDesc_NuclearCell_256.png",
    "Coal Generator": "https://static.satisfactory-calculator.com/img/gameUI/CoalGenerator_256.png",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
};
